services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - './apps/reservations/.env'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - './apps/auth/.env'
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - './apps/payments/.env'
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  # gateway:
  #   build:
  #     context: ./gateway
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - reservations
  #     - auth
  reservations-db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: none
  auth-db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: none
