services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - './apps/reservations/.env'
    environment:
      - SELF_NAME=reservations-1
      - SELF_HOST=reservations-1
      - SELF_PORT=3001
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - service-discovery

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - './apps/auth/.env'
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - service-discovery

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - './apps/payments/.env'
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
    depends_on:
      - service-discovery

  gateway:
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    ports:
      - '8888:8888'

  service-discovery:
    build:
      context: ./service_discovery
      dockerfile: ./Dockerfile
    ports:
      - '7777:7777'

  reservations-db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: none
  auth-db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: none
